version: '3'

services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali_container
    networks:
      - my_network
    volumes:
      - ./data/:/home/kali_data
    tty: true
    entrypoint: >
      /bin/bash -c "apt update && apt install -y hydra inetutils-ping vim lftp curl && /bin/bash"

  ftp_server:
    image: delfer/alpine-ftp-server
    container_name: ftp_container
    networks:
      - my_network
    ports:
      - "21:21"
    environment:
      - USERS=user|strongpassword123
    volumes:
      - ./ftpdata:/ftp/user/
  # web_app:
  #   container_name: web_app
  #   image: gitlab.cylab.be:8081/cylab/play/brute-force
  #   ports:
  #   - "8000:80"
  #   environment:
  #     PASSWORD: "@123456789"
  #   restart: "unless-stopped"
  #   networks:
  #     - my_network
  web-application-dvwa:
    image: vulnerables/web-dvwa:1.9
    container_name: dvwa_container
    networks:
      - my_network
    ports:
      - "8080:80"

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
